"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the
first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the
even-valued terms.
"""
__author__ = 'cjpowell'


def fibonacci(limit):
    results = [0, 1]
    while results[-1] < limit:
        results.append(results[-1] + results[-2])
    return results


def sum_evens(array):
    results = 0
    for num in array:
        if num % 2 == 0:
            results += num
    return results


def main():
    limit = input('Enter a limit: ')
    print sum_evens(fibonacci(limit))

if __name__ == '__main__':
    main()